name: Pre-Release

# 触发器
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
      - 'doc/**'
      - 'image/**'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'
      - 'doc/**'
      - 'image/**'

jobs:
  build:

    runs-on: ubuntu-latest
    # 设置JDK为17
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Checkout Secret
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.SECRET_REPO }}
        token: ${{ secrets.TOKEN }}                     # 连接仓库的Token
        path: secret
    # 准备secret文件
    - name: Copy Secret Files
      run: |
        cd secret/NightScreen
        cp key.jks ../..
        cp secret.gradle ../..
    # 清理secret文件
    - name: Clean Temp Secret Files
      run: |
        rm -rf ./secret
    # 打包
    - name: Build with Gradle
      run: |
        bash ./gradlew assembleGitHub
    # 存档打包的文件
    - name: Upload Pre-Release Apk
      uses: actions/upload-artifact@v3
      with:
        name: Pre-Release Apk
        path: app/build/outputs/apk/GitHub/release/*.apk